replicas: 1
serviceaccount: ""
namespace: pet-clinic-app
image:
  repository: techiescamp/kube-petclinic-app
  tag: 3.0.0
  pullPolicy: IfNotPresent
env:
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
ports:
- name:  http
  containerPort: 8080
  protocol: TCP
  targetPort: 8080
  nodePort: 30080
startupProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  failureThreshold: 30
  periodSeconds: 20
  initialDelaySeconds: 180
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 10
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  periodSeconds: 15
  failureThreshold: 3
  timeoutSeconds: 10
