rabbithost: "ei-client-rabbitmq.gadm-eicustomerconnector.svc.cluster.local"
rabbitport: "5672"
rusername: "ei-client"
rabbitmq_ssl_enable: "false"
GetCanonicalIncidentDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/getCanIncidentDetails/{uri.var.sys_id}/"
PersistAssigenedToEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/getAssignmentGroupBasedOnLabel/{uri.var.assignment_group}/"
PostCanonicalDataToDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlconnecttestei/1.0/Persist/incident/transaction?createdby={uri.var.createdby}"
PostCanonicalDataToNoSQLDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Stream/can/transaction/"
PushAttachmentToDataLakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/byte/attachment/transaction/"
MasterDataToCanonicalDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/form/choice/reference?createdby={uri.var.createdby}"
UserDataToCanonicalDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/form/user/reference?createdby={uri.var.createdby}"
MasterDataToRawDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/raw/choice/reference"
UserDataToRawDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/raw/user/reference"
UserGroupToRawDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/raw/usergroup/reference"
UserGroupMemberToRawDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/raw/usergroupmember/reference"
UserGroupToCanonicalDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/form/usergroup/reference?createdby={uri.var.createdby}"
UserGroupMemeberToCanonicalDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/form/usergroupmember/reference?createdby={uri.var.createdby}"
GetAttachmentDetailsDatalakeEP_VAR: "https://wso2-gateway.gadm.eks-test.na.eafcore.com/dlei/1.0/Persist/getAttachmentDetails/{uri.var.sys_id}"
SNOWUpdateRetryEP_VAR: "http://localhost:8290/retrymessage/snowupdateretry"
NewTicketEP_VAR: "http://localhost:8290/itsm/newIncidentTicket" 