apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinicapp.fullname" . }}
  labels:
    app: {{ include "petclinicapp.name" . }}
    chart: {{ include "petclinicapp.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  {{- range .Values.ports }}
  - port: {{ .containerPort }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
  {{- end }}
  selector:
    {{- include "petclinicapp.labels" . | nindent 4 }}