database=mysql
spring.datasource.url=jdbc:mysql://petclinicapp-mysql-service.petclinic.svc.cluster.local:3306/petclinic
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=always
spring.thymeleaf.mode=HTML
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true
spring.messages.basename=messages/messages
management.endpoints.web.exposure.include=*
logging.level.org.springframework=INFO
spring.web.resources.cache.cachecontrol.max-age=12h