apiVersion: v1
kind: Secret
metadata:
  name: {{include "mysql.fullname" .}}-secret
type: {{ .Values.secret.type }}
data:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
