apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-service
spec:
  type: NodePort
  selector:
    {{- include "mysql.labels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080